


































  0%|                                           | 227/105560 [01:13<9:04:54,  3.22it/s]Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/aj3051/anaconda3/envs/backpack/lib/python3.11/linecache.py", line 46, in getlines
  File "/home/aj3051/anaconda3/envs/backpack/lib/python3.11/linecache.py", line 93, in updatecache
    stat = os.stat(fullname)
           ^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Original exception was:
Traceback (most recent call last):
  File "/local/rcs/aj3051/equitune/train.py", line 180, in <module>
    loss.backward()
  File "/home/aj3051/anaconda3/envs/backpack/lib/python3.11/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/home/aj3051/anaconda3/envs/backpack/lib/python3.11/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt